"""The durable key format, stated once as BYTES: the only place in the suite that does.

**Why this file exists.** A suite can be exhaustively coupled to a representation and pin none of
it. Renaming the `step` arm tag at its producer sites, or the `occ` term, breaks many tests whose
literals spell the old bytes, yet none of them catches a *defective* version of that change: the
failures are loud and the property is unguarded.

**The rule that makes this table an instrument rather than a mirror: every expected value here is
AUTHORED from the design, never captured from output.** A table generated by running the code
agrees with whatever the code does, so it cannot fail. If you are tempted to paste a `.stored()`
you just printed, stop: the paste is the defect. Read the key grammar and write what it says it
should be; a disagreement with the code is then a finding in one direction or the other.

**How to know the rule was followed**, since a promise in a docstring is not a check. Mutate a
rendering and re-run: rename the `step` arm in `handlers/base.step_key`, or `OCCURRENCE_SIGIL` in
`grammar`. **This file must redden.** A captured table goes GREEN under that mutation, which is
what exposes it, and that is the whole of the check.

Other tests redden under the same mutation too, because armed expectation literals elsewhere in
the suite spell the arm. That coupling is why this file has to exist; measure the mutation
against THIS file, not against the suite.

Role: adversarial. These rows exist to fail when the format moves.
"""

from datetime import UTC, datetime

import pytest
from _authority import approve_park

from effective.budget import budget_grant_name, chain_grant_name, depth_grant_name
from effective.code import _action_key, _segment_key
from effective.counterfactual import fork_scoped
from effective.domain import CallTool
from effective.govern import GateState
from effective.handlers.base import op_key, step_key
from effective.handlers.durable import (
    fork_event_name,
    respawn_name,
    respawned_name,
    wake_race_at_time,
    wake_race_on_event,
)
from effective.keys import Key, Segment, compose_key
from effective.keys.registry import KeyMap
from effective.ops import AppendLedgerRow, AwaitEvent, LedgerRow, Step, StoreArtifact

pytestmark = pytest.mark.adversarial


def _dop() -> CallTool[str]:
    return CallTool(name="t", result_schema=str)


# (label, how the substrate mints it, the bytes the DESIGN says it must be)
#
# The label is the pytest id, so a failure names the namespace rather than an index. Ordered by
# the design's own sections: the arm terms first (§3a), then the authority families (§3b), then
# the author namespaces (§3c).
ROWS: list[tuple[str, object, str]] = [
    # --- §3a the arm terms ---------------------------------------------------------------
    # A bare author name is one ATOM, so it lands in a coordinate — where `NAME` admits `_`.
    ("step/atom", lambda: step_key("assess_request"), "step:assess_request"),
    # A name that carries structure is a KEY, and a key extends the sequence: that is what `;` is.
    ("step/structured", lambda: step_key("tool:charge-card"), "step;tool:charge-card"),
    (
        "event",
        lambda: op_key(AwaitEvent(name=Key.parse("review:m1"), schema=str)),
        "event;review:m1",
    ),
    (
        "ledger",
        lambda: op_key(AppendLedgerRow(row=LedgerRow(event_id=Key.parse("reviewed:m1")))),
        "ledger;reviewed:m1",
    ),
    # --- occurrence: the grammar's terminal SUFFIX, omitted at its default of 1 (§1g) ------
    (
        "occ/first-is-omitted",
        lambda: Key.parse("tool:charge-card").occurrence(1),
        "tool:charge-card",
    ),
    ("occ/second", lambda: Key.parse("tool:charge-card").occurrence(2), "tool:charge-card#2"),
    # --- §3b the fork family --------------------------------------------------------------
    (
        "fork",
        lambda: fork_event_name("cf-a", Key.parse("review:m1")),
        "fork:cf-a;review:m1",
    ),
    (
        "hyp",
        lambda: fork_scoped(Segment("cf-a"), Key.parse("reviewed:m1")),
        "hyp:cf-a;reviewed:m1",
    ),
    ("respawn", lambda: respawn_name("r1", 2), "respawn:r1,2"),
    ("respawned", lambda: respawned_name("r1", 2), "respawned:r1,2"),
    # --- the authority families, and §1b's optional coordinates ----------------------------
    ("budget-grant", lambda: budget_grant_name("r1", 0), "budget-grant:r1,0"),
    ("chain-grant", lambda: chain_grant_name("r1", 0), "chain-grant:r1,0"),
    # bare = required, named = optional: `depth` is at its default and is therefore OMITTED.
    (
        "depth-grant/default",
        lambda: depth_grant_name("r1", generation=0, depth=0),
        "depth-grant:r1,0",
    ),
    (
        "depth-grant/present",
        lambda: depth_grant_name("r1", generation=0, depth=2),
        "depth-grant:r1,0,depth=2",
    ),
    # §1b's worked example, byte for byte: both optionals at their defaults, so neither is written.
    (
        "govern/defaults",
        lambda: GateState(gate="approve", run_id="r1", op_key="step;tool:charge-card").park_name,
        "govern:approve,r1;step;tool:charge-card",
    ),
    # And what the NAMED form buys that a positional one could not: skip one, give a later one.
    (
        "govern/skips-an-optional",
        lambda: (
            GateState(
                gate="approve", run_id="r1", op_key="step;tool:charge-card", occurrence=3
            ).park_name
        ),
        "govern:approve,r1,occurrence=3;step;tool:charge-card",
    ),
    # --- §3c the author namespaces ----------------------------------------------------------
    ("tool", lambda: compose_key(t"tool:{Segment('charge-card')}"), "tool:charge-card"),
    # Arity plus a literal discriminator separates the substrate's reserved tools from an author's.
    ("tool/spawn", lambda: compose_key(t"tool:spawn,{Segment('c1')}"), "tool:spawn,c1"),
    (
        "tool/interrupt",
        lambda: compose_key(t"tool:interrupt,{Segment('pre')}"),
        "tool:interrupt,pre",
    ),
    # `run_code`: the discriminator LEADS and the identity TRAILS, because a splice must be last.
    ("code/seg-atom", lambda: _segment_key("audit", False, 0), "code:seg,0,audit"),
    ("code/seg-structured", lambda: _segment_key("act:t0", True, 0), "code;seg:0;act:t0"),
    (
        "code/action-atom",
        lambda: _action_key("audit", False, 1, "read_file"),
        "code:action,1,audit;tool:read_file",
    ),
    (
        "code/action-structured",
        lambda: _action_key("act:t0", True, 1, "read_file"),
        "code;action:1;tool:read_file;act:t0",
    ),
    # --- the gather frame's wake-race park -----------------------------------------------------
    #
    # A name built by an f-string is invisible to `--key-registry`, so no row can call it — and
    # this is precisely the family where the automated checks go quiet:
    # a mis-grouped `gather:0,wake-race,0,ev` carries every atom of the real key, in order, is
    # well-formed and arm-reachable, and passes BOTH the grammar gate and a
    # content-conservation diff. Only a stated byte string separates it.
    #
    # Two variants, separated by the SHAPE of the wake condition rather than by an invented
    # literal: an event is a `Key`, so it extends the sequence as a term; a time is a value, so it
    # rides as a coordinate.
    (
        "gather/wake-race-event",
        lambda: wake_race_on_event(0, 1, Key.parse("ev")),
        "gather:0;wake-race:1;ev",
    ),
    # A STRUCTURED await name, which a coordinate splice could not carry.
    (
        "gather/wake-race-event-structured",
        lambda: wake_race_on_event(0, 1, Key.parse("approve;r1")),
        "gather:0;wake-race:1;approve;r1",
    ),
    # `epoch-1767225600.0` is AUTHORED, not captured: 2026-01-01T00:00:00Z is 1767225600 seconds
    # after the epoch — verified against `date -u -d '2026-01-01 00:00:00' +%s`, an oracle with no
    # stake in our code — and Python's float repr writes the integral value with a `.0` tail.
    (
        "gather/wake-race-time",
        lambda: wake_race_at_time(0, 1, datetime(2026, 1, 1, tzinfo=UTC)),
        "gather:0;wake-race:1,epoch-1767225600.0",
    ),
    # Sub-second, so the row states that the fraction SURVIVES rather than being truncated to the
    # second — the property a wake time needs if two races a fraction apart are to stay distinct.
    (
        "gather/wake-race-time-fractional",
        lambda: wake_race_at_time(0, 1, datetime(2026, 1, 1, 0, 0, 0, 500000, tzinfo=UTC)),
        "gather:0;wake-race:1,epoch-1767225600.5",
    ),
]


@pytest.mark.parametrize(
    ("mint", "expected"),
    [(mint, expected) for _label, mint, expected in ROWS],
    ids=[label for label, _mint, _expected in ROWS],
)
def test_the_durable_format(mint, expected) -> None:
    assert mint().stored() == expected


def test_the_artifact_key_is_a_mime_PATH_and_an_algorithm_prefixed_digest() -> None:
    """The one arm whose bytes cannot be authored, kept out of the table on purpose.

    An artifact key is content-addressed, so its last coordinate is a hash of the payload — and
    transcribing a hash into the table would be pasting output, the exact thing the table's rule
    forbids. What IS authorable is the structure §1d and §3c give it, so that is what this pins:
    the MIME type is a two-atom PATH in one coordinate (`message/rfc822` IS `type/subtype`, RFC
    2045), and the digest is ALGORITHM-PREFIXED so a lexer can name its kind without being told
    what the field means. Bare hex reads equally as a name; `sha256-` does not."""
    key = op_key(StoreArtifact(value={"k": 1}, content_type="message/rfc822"))
    (term,) = key.terms()
    assert term.tag == "artifact"
    mime, digest = term.coordinates
    assert [atom.text for atom in mime.atoms] == ["message", "rfc822"]
    assert digest.path.startswith("sha256-"), digest.path


def test_every_row_is_in_the_language_it_claims_to_pin() -> None:
    """A row asserting bytes the grammar refuses would pin a format nothing can read back.

    Cheap, and the class is real: rows such as `hyp:r-fork;reviewed;m1` and
    `approve;front-door:a:b` can be *asserted* while neither is mintable; one parses as something
    else, one does not parse at all."""
    for label, _mint, expected in ROWS:
        assert Key.parse(expected).terms(), label


def test_the_table_is_sized_to_the_REGISTRY_so_a_gap_is_visible() -> None:
    """Anti-vacuity with a countable domain, which is the coverage argument for a table.

    The registry knows every namespace the tree mints (`--key-registry` over `src` + `examples`).
    A tag with no row here is a namespace whose bytes nothing states — a visible gap rather than
    an invisible one, which is the `what does the enforcer SCAN` question answered by
    construction.

    It asserts a FLOOR rather than equality on purpose: `examples/` mints author namespaces
    (`iterate`, `structural`, `talk`) whose bytes are the example's business, not the substrate's.
    Raise the floor when a substrate namespace is added, and the failure will say so."""
    covered = {label.split("/")[0] for label, _mint, _expected in ROWS}
    # `artifact` is content-addressed, so its bytes cannot be authored; the test above pins its
    # STRUCTURE instead. Named here rather than silently absent, because a gap with a reason is a
    # decision and a gap without one is an oversight.
    covered |= {"artifact"}
    registered = set(KeyMap.load().variants)
    substrate = {
        "step",
        "event",
        "ledger",
        "artifact",
        "fork",
        "hyp",
        "respawn",
        "respawned",
        "budget-grant",
        "chain-grant",
        "depth-grant",
        "govern",
        "tool",
        "code",
        # `gather` is in `ARM_TAGS` and `FRAME_ARMS`, so it is substrate.
        "gather",
    }
    missing = sorted(substrate - covered)
    assert not missing, f"substrate namespaces with no byte row: {missing}"
    assert substrate <= registered, sorted(substrate - registered)


def test_a_step_name_and_its_key_are_not_the_same_string() -> None:
    """The arm term's whole purpose, stated as a property rather than as a spelling.

    It survives a rename of the arm — unlike every row above, deliberately. The table pins the
    BYTES and this pins the STRUCTURE, and a suite needs both: bytes catch a silent rendering
    change, structure says why the bytes are what they are."""
    for name in ("assess_request", "tool:charge-card", "ledger;x"):
        assert op_key(Step(name=name, op=_dop())).stored() != name


# --- reachability: well-formed is not the same as MINTABLE ---------------------------------
#
# `test_grammar` pinned `gather:0,0;event;step;tool:foo` in three places and was GREEN, because
# what it asserted was that the row PARSES. The row is well formed and unmintable: it says "await
# an event whose NAME is a step's checkpoint key", and nothing emits one. Parsing is necessary and
# not sufficient, and the two questions read alike enough that a test named for the first looks
# like it answers the second.
#
# The question is decidable here, which is why it is checked rather than reasoned about: the arm
# set is CLOSED, so the key space is a qualification scheme over a finite tag alphabet and not a
# Turing-complete one. "Could anything mint this?" is a lookup.


def test_an_op_identity_is_refused_as_an_await_ADDRESS() -> None:
    """The narrowing the grammar cannot do for itself.

    An arm's payload is typed `Key`, i.e. ANY key — so `event;{name}` admits a step's identity as
    far as the parser is concerned. What rules it out is the DOMAIN: an await's name is the
    address an emitter delivers to, and no producer emits an event named after a checkpoint."""
    from effective.ops import event_name

    for identity in ("step;tool:foo", "event;foo", "ledger;reviewed:m1"):
        with pytest.raises(ValueError, match="opens with an op ARM"):
            event_name(identity)  # the `str` door
        with pytest.raises(ValueError, match="opens with an op ARM"):
            event_name(Key.parse(identity))  # and the `Key` door, which skips the author fence


def test_a_substrate_address_may_CONTAIN_an_arm_deeper_in() -> None:
    """Only the LEADING tag decides, and this is the case that forces that.

    The permission layer composes `approve;{placed_key}`, and the placed key is frequently a
    step's. `event;approve;step;tool:charge-card` is real, minted, and correct — what makes it an
    address is that it opens with `approve`. A rule that refused an arm ANYWHERE in the payload
    would refuse the substrate's own approvals, which is the over-refusal to watch for whenever a
    structural rule gets tightened."""
    from effective.ops import event_name

    address = approve_park(Key.parse("step;tool:charge-card"))
    assert event_name(address).stored() == "approve;step;tool:charge-card"


def test_the_design_row_that_shipped_unmintable_stays_unmintable() -> None:
    """A regression pin on the specific artifact, because it survived review in three places.

    The key grammar's design once carried the row
    `gather:0:0:event:foo -> gather:0,0;event;step;tool:foo`. The corrected row is what the
    substrate actually mints for a gathered branch's await."""
    from effective.keys.frame import leads_with_an_arm

    assert leads_with_an_arm("step;tool:foo"), "the payload the bad row put in address position"
    assert not leads_with_an_arm("foo"), "what the left column actually named"


# --- the splice's declared domain -----------------------------------------------------------
#
# `ops.event_name` refuses an op identity at the address DOOR; these pin the two enforcers
# behind it: the COMPOSER, which refuses a wrong key one template at a time, and the REGISTRY,
# which refuses a wrong key one finished string at a time. Neither subsumes the other, and the
# pair below says why: the composer cannot see a key that arrives through an honest frame, and
# the registry cannot see a template.


def test_the_composer_refuses_an_op_identity_in_an_ADDRESS_splice() -> None:
    """`compose_key`, not just `event_name`. An arm's payload declared plain `Key` — i.e. ANY
    key — lets the composer mint `event;step;tool:foo`, a well-formed key that says *await an
    event whose name is a checkpoint*. No producer emits one, so `domain=address` refuses it."""
    from effective.keys import compose_key

    with pytest.raises(ValueError, match="domain=address"):
        # lint: terminal-hole — a `Key`, which the composer splices by INDUCTION; a `Segment`
        # here would be the flatten the splice exists to avoid.
        compose_key(t"event;{Key.parse('step;tool:foo'):domain=address}")


def test_an_UNDECLARED_splice_is_refused_rather_than_admitted() -> None:
    """The default is the whole design decision. A splice that declares nothing is exactly the
    hole this closes, so it is refused; `domain=any` is how you say *anything*, where the next
    reader can see that somebody decided it rather than omitted it."""
    from effective.keys import compose_key

    inner = Key.parse("review:m1")
    with pytest.raises(ValueError, match="declares no domain="):
        # lint: terminal-hole — a `Key`, spliced by induction; see the test above.
        compose_key(t"event;{inner}")
    # lint: terminal-hole — likewise.
    assert compose_key(t"wrap;{inner:domain=any}").stored() == "wrap;review:m1"


def test_a_STEP_splice_admits_a_name_that_looks_like_an_arm() -> None:
    """The over-refusal guard. A step's payload is the name its AUTHOR chose, and the arm is
    what makes any name safe: `step;ledger:x` is disjoint from `ledger:x`
    by construction, so no author name needs fencing. Declaring `domain=address` instead refuses
    `step_key("ledger;x")`, which is a legal name."""
    assert step_key("ledger;x").stored() == "step;ledger;x"
    assert step_key("event;q").stored() == "step;event;q"


def test_the_registry_refuses_to_EXPLAIN_a_key_no_producer_mints() -> None:
    """The row this whole item started from, as a pin.

    `KeyMap.explain("gather:0,0;event;step;tool:foo")` must not answer. `_unframe` peels terms
    from the left until the remainder decodes, so unguarded it strips `gather:0,0` AND `event`
    and reports the producer of what is left — a source map naming a producer for a key no
    producer makes."""
    from effective.keys.registry import KeyMap, UnknownTag

    keymap = KeyMap.load()
    with pytest.raises(UnknownTag, match="UNMINTABLE"):
        keymap.explain("gather:0,0;event;step;tool:foo")
    # and the corrected row still decodes, which is the half that must NOT move
    assert keymap.explain("gather:0,0;event;foo").site.startswith("src/effective/api.py")


def test_reachability_stops_at_the_step_arm_and_ignores_a_frame() -> None:
    """The two boundaries of `grammar.unmintable`, each found by running it rather than by
    reading. Past a bare `step` everything is a name the author chose, so no structural claim
    survives; and a term WITH coordinates is a frame that wraps rather than an arm that
    addresses."""
    from effective.keys.frame import unmintable

    assert unmintable("event;step;tool:foo") is not None
    assert unmintable("gather:0,0;event;step;tool:foo") is not None, "a frame does not launder it"
    assert unmintable("step;event;q") is None, "author territory begins at the step arm"
    assert unmintable("gather:0,0;event;foo") is None, "the corrected design row"
    assert unmintable("event;approve;step;tool:charge-card") is None, "a real approval address"


def test_a_FRAME_is_transparent_to_the_domain() -> None:
    """The correction that took three attempts, pinned so it takes none next time.

    `gather` is reserved in `ARM_TAGS` like every op's tag and then never leads an identity — a
    gather is placed by the walk, and `gather:{g},{i};…` FRAMES whatever follows. So the same
    leading tag sits in front of an address and an identity, and a domain rule that stopped at it
    refused `parked.py`'s own park name. Declaring `domain=any` everywhere a frame can appear was
    the wrong fix; looking past the frame, once, in `admits`, is the right one."""
    from effective.keys.frame import admits, unmintable
    from effective.keys.grammar import Domain

    assert admits(Domain.ADDRESS, "gather:0,0;ev0:r1"), "a branch's park, which parked.py mints"
    assert not admits(Domain.ADDRESS, "gather:0,0;event;foo"), "a framed IDENTITY is still one"
    assert admits(Domain.IDENTITY, "gather:0,0;event;foo")
    assert unmintable("event;gather:0,0;ev:r1") is None, "the key parked.py actually composes"


def test_a_shape_DECODES_a_key_that_omitted_an_optional_coordinate() -> None:
    """The source map spans the same arity RANGE the template renders.

    An optional coordinate is omitted at its default (§1b), so `govern:`'s four-coordinate
    template renders two, three or four of them — and `Shape.decode` compared declared count to
    rendered count, so it matched only the maximal spelling. Every key that left an optional out
    fell through to `_unframe`, which peeled it down to the arm and reported `step_key`'s line: a
    confident decode naming the wrong producer, not an error.

    `separated` learned the range when `_arity_range` landed the same day; this reader did not.
    The two are one fact seen from either side, which is why this pins BOTH spellings."""
    from effective.budget import depth_grant_name
    from effective.govern import GateState
    from effective.keys.registry import KeyMap

    keymap = KeyMap.load()
    omitted = GateState(gate="approve", run_id="r1", op_key="step;tool:charge-card").park_name
    present = GateState(gate="spend", run_id="r-1", op_key="step;tool:x", occurrence=2).park_name
    for key, expected in (
        (omitted, {"gate": "approve", "run_id": "r1", "op_key": "step;tool:charge-card"}),
        (present, {"gate": "spend", "run_id": "r-1", "occurrence": "2", "op_key": "step;tool:x"}),
    ):
        explained = keymap.explain(key.stored())
        assert "govern.py" in explained.site, f"{key.stored()!r} named {explained.site}"
        assert explained.bindings == expected
    # the same range, one namespace over — and `depth-grant:r1,0` is the COMMON spelling
    assert keymap.explain(depth_grant_name("r1", generation=0, depth=0).stored()).bindings == {
        "run_id": "r1",
        "generation": "0",
    }
