"""initial: the append-only ledger

Revision ID: 0001
Revises:
Create Date: 2026-05-30
"""

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel type availability in autogenerated code)
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "ledger",
        sa.Column("seq", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("workflow_run_id", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.UniqueConstraint("event_id", name="uq_ledger_event_id"),
    )
    op.create_index("ix_ledger_workflow_run_id", "ledger", ["workflow_run_id"])

    # Append-only ledger: block UPDATE/DELETE even for the owner.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION ledger_append_only() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'ledger is append-only (% blocked)', TG_OP;
        END;
        $$;
        """
    )
    op.execute("DROP TRIGGER IF EXISTS ledger_no_mutate ON ledger;")
    op.execute(
        "CREATE TRIGGER ledger_no_mutate BEFORE UPDATE OR DELETE ON ledger "
        "FOR EACH ROW EXECUTE FUNCTION ledger_append_only();"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS ledger_no_mutate ON ledger;")
    op.execute("DROP FUNCTION IF EXISTS ledger_append_only();")
    op.drop_table("ledger")
